### ISSUE TITLE
Blue Ribbon Panel List

### ISSUE THREAD

**Issue by jsonin** [standardhealth/shr_design#1]
Determine, contact, and test SHR with key medical, policy, epatient advocates.

**Comment by jsnichols** [comment]
I recommend we invite Abraham Verghese. He's a proponent of teaching the history and physical exam to medical students, and would have a vested interest in ensuring that our data model doesn't sacrifice the unique diagnostic skills of a well trained physician-as-sensor.

[http://www.nytimes.com/2010/10/12/health/12profile.html?_r=0](url)

**Comment by susanhaas** [comment]
Second that concept and that guy

**Comment by jsnichols** [comment]
CAPT Denise Koo, MD, MPH, USPHS is Senior Advisor to the Assistant Director for Policy at CDC. She is the leading authority within CDC on leveraging social determinants to improve health and for integration between public health and primary care. And a personal connection of mine.

**Comment by jsnichols** [comment]
Steven Woolf, MD, MPH, professor of Family Medicine and Population Health at VCU, and director of the Center for Society and Health. Leading researcher in SDOH. Editor of the IOM/NAM report U.S. Health in International Perspective: Shorter Lives, Poorer Health (2013)

[http://www.nap.edu/catalog/13497/us-health-in-international-perspective-shorter-lives-poorer-health](url)
