### ISSUE TITLE
Does SHR include "patient agency" issues

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr_design#13]
I think it should, but that can be a detailed, state by state issue (thank you, Southern states' right movement!).

From: Harry Sleeper <harrysleeper@gmail.com>
Sent: Friday, July 15, 2016 11:35:57 AM
To: Sleeper, Harry A.
Subject: Does SHR include "patient agency" issues

[http://www.honoringchoicesmass.com/](url)

**Comment by jsnichols** [comment]
This is addressed currently in at least 4 ways.

First, as a "Preferences" entry under the Care Plan.
Second, with ability for a patient to "Comment" on any entry within the SHR, e.g. I may comment that a procedure that I underwent was uncomfortable, and that I do not wish to undergo that procedure again.
Third and Fourth, fundamentally with the presence of a Care Plan and Advanced Directives within the SHR itself.

Any other comments?

**Comment by jsnichols** [comment]
Also, by tracking "patient concerns" with the same fidelity as "problems/diagnoses"

**Comment by susanhaas** [comment]
A mechanics/ competing/conceptual question: if the SHR is the repository into which and out of which whatever standing EMRs send/receive information (please correct me if my model is wrong) then where are patients entering info--directly into SHR (where docs are not entering) or into their provider's EHR?
Susan
