### ISSUE TITLE
Migration as a key differentiator between SHR and competing approaches to data modeling

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr_design#14]
SHR information modeling efforts have, to date, focused on definition of the data elements of an SHR. We are rapidly moving towards introduction of a governance process that will manage adoption and evolve the SHR over time. 

Meanwhile the SHR may not be sufficiently differentiated from competing information models in its present and near-future state. All models seek to facilitate secure and comprehensive data exchange. SHR is positioned to leverage certain existing approaches (e.g. CCDA, FHIR) in achieving its ultimate ends, and may not be freed completely from inherent limitations of these models. So what justifies adoption of SHR universally, and over competing approaches?

**Our strategy for SHR must explicitly address the process of _migration_, from the current state of health data representation to our idealized future state.** 

If SHR can demonstrate to sponsors, vendors, clinicians and consumers, "Not only have we defined the ideal future state, but we have a specific technical open-sourced roadmap to get everyone there," then we will have made SHR adoption a feasible reality.

If not, my fear is that SHR will be received as: "Nice spreadsheet (the SHR). I'd love to have that. But how to I get 7+ years of historic health data loaded into that, because without that the ability to do that, it is not worth the investment to adopt new approach to data modeling, however vastly improved, And P.S., I've had to do that before, when we [adopted/transitioned to] our [first/latest] EHR [Epic/Cerner/Allscripts/NextGen/Centricity/whatever] and it took years off my life, so I'd rather be locked into our current (ineffective, non-interoperable) system, than have to ever utter the word 'preload' again in my life."

**The mere existence of SHR does not provide a 10x acceleration in desired health outcomes, streamlining the technical process of its adoption (i.e. migration) does.**
The market is yearning for an alternative, unified, well-governed approach to health information modeling. Let us invest our significant technical capabilities in developing the on-ramp to that approach.

**Comment by markkramerus** [comment]
Use normalized English language. Avoid complex coding systems. Let the docs say what they want to say. "PT denies chest pain" is completely clear and unambiguous (it can be understood to be an exclusion statement whose source is the patient, whose condition is pain in the body location "chest"). Even so, I don't think this quite hits the "migration" target. Any other ideas?

**Comment by jsnichols** [comment]
I like it. Here's a  use case leveraging "Normalized English language." 

I have terabytes upon terabytes of scanned medical documentation previously archived in my old EHR, that I want to import into my new SHR/EHR. 

Because the SHR is based on normalized English language (or Medicalese), it is computationally far easier to parse documents for SHR elements. So you can OCR your terabytes of  documents and batch process into structured SHR data. Any changes to core SHR data elements (e.g. allergic to penicillin) discovered in these documents could be confirmed by clinicians and/or the patient themselves. 

By **migration**, I mean "how to we get from the current EHR state to the ideal future SHR state." What are the technical/political/economic/social glide paths?
