### ISSUE TITLE
Map out the SHR evolution over the next X units of time

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr_design#16]
&gt; From: "Sleeper, Harry A." 
&gt; Date: July 15, 2016 at 8:47:35 PM EDT
&gt; To: "Quilty, Mary T." , Joey Nichols 
&gt; Cc: shr-project-list Standard Health Record 10x Project List 
&gt; Subject: RE: From SHR to the Precision Health Record (after Eric Topol)
&gt; 
&gt; Love it.
&gt; 
&gt; Capture the core, 
&gt; add more and more, 
&gt; with the petal to the metal.
&gt; 
&gt; Joey, you are arguing for a very rapid evolution.
&gt; That's consistent with the SHR concept of operations; it is hinted at in the SHR BRP Charter; it is visualized in the basic SHR depiction (see attached); and it is implied by the open source nature of the SHR project.
&gt; 
&gt; Help us define "rapid evolution"!
&gt; Please map out the SHR evolution over the next X units of time.
&gt; Ok?
&gt; 
&gt; Press!
&gt; 
&gt; ...H
&gt; 
&gt;  
&gt; From: Quilty, Mary T.
&gt; Sent: Friday, July 15, 2016 5:46:37 PM
&gt; To: Joey Nichols
&gt; Cc: Sleeper, Harry A.; shr-project-list Standard Health Record 10x Project List
&gt; Subject: RE: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; Let me catch up with these links…and form some thoughts to reply to your questions posed below.
&gt;  
&gt; I get what you’re saying. I don’t see the SHR as it is now as a final version, but it sounds like you are getting at there needs to be a fundamental shift/addition in framing and/or content (maybe even if it isn’t materializing in v.001?).
&gt;  
&gt; I agree, the sociodemogs in there now are what we needed…we’re catching up medicine or ‘healthcare’ more specifically with their inclusion. I always assumed lots of folks in the health space could get at the SHR. Wellness/healthcare/medicine can’t rely on the PCP or ER. There’s an urgent need NOW for a wide range of providers to get their hands on this data.
&gt;  
&gt; I wonder if the ‘community’ will bite if we make it bigger or if we start with getting the basics right. I honestly don’t know…it may be divided.
&gt;  
&gt; From: Joey Nichols [mailto:jsnichols@gmail.com] 
&gt; Sent: Friday, July 15, 2016 5:29 PM
&gt; To: Quilty, Mary T. 
&gt; Cc: Sleeper, Harry A. ; shr-project-list Standard Health Record 10x Project List 
&gt; Subject: Re: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; Mary thanks for the helpful clarification.
&gt;  
&gt; I am trying to challenge SHR project to push the scope of the clinical practice of medicine by broadening the scope of data available in the SHR. I am trying to figure out how to make SHR the thing we need five years from now, not the thing that we needed five years ago. 
&gt;  
&gt; So "Does SHR support Precision Medicine?" and "Is the SHR capable of serving as a PHR?" where PHR = Precision Health Record?
&gt;  
&gt; Precision Medicine is not a caramel coating that you can embed nuts into. For me, great examples of "nuts" are individual or population level visualization tools, clinical workflow enhancements, patient facing apps that facilitate behavior change, and the like. SMART-on-FHIR might be a flavor of "caramel". But the "caramel and nuts" depend upon the contents of the SHR. But you can't support Precision Medicine in the medium term future with our current vision of SHR. 
&gt;  
&gt; Although it would be a great start... http://ift.tt/29X3peR
&gt;  
&gt; There is other exciting work to leverage...
&gt;  
&gt; http://ift.tt/1LHPPWs
&gt;  
&gt; UPMC Enterprises commits to creating an effort called REDA (Real-time Enterprise Data Abstraction) in 2016, which will make legacy EHR data available to applications and services, including those needed for precision medicine, through a FHIR API interface.
&gt;  
&gt; Inova Health System, a non-profit healthcare system serving more than 2 million people per year, is committed to completely transform itself into a precision medicine health organization. Today, the organization is announcing that it will set up a new venture investment fund in excess of $100 million focused exclusively on precision medicine.
&gt;  
&gt; ...What can we learn from UPMC about the SHR/PHR question? 
&gt;  
&gt; ...What would Inova need from an SHR to support Precision Medicine?
&gt;  
&gt; 
&gt; -JSN-
&gt; 
&gt; Joey Nichols
&gt; jsnichols@gmail.com
&gt; 713.398.5225
&gt;  
&gt; On Fri, Jul 15, 2016 at 5:14 PM, Quilty, Mary T.  wrote:
&gt; I was referring to the SHR deck (the covered apples) and the idea of HIEs and others in this space having an opportunity to leverage their work by providing the different flavors or looks of the SHR to folks and being allies to the SHR initiative…so in that case, I suppose they would be augmentations…and in the event the individual/patient wanted that information included in their SHR it could be an extension…I assume the SHR will be extensible as new areas emerge for inclusion.
&gt;  
&gt; From: Sleeper, Harry A. 
&gt; Sent: Friday, July 15, 2016 5:11 PM
&gt; To: Quilty, Mary T. ; Joey Nichols ; shr-project-list Standard Health Record 10x Project List 
&gt; 
&gt; Subject: RE: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; Are "carmel and nuts" SHR extensions or EHR augmentation data?
&gt; 
&gt; From: Quilty, Mary T.
&gt; Sent: Friday, July 15, 2016 4:54:27 PM
&gt; To: Sleeper, Harry A.; Joey Nichols; shr-project-list Standard Health Record 10x Project List
&gt; Subject: RE: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; Building on my prior response…is it all in the SHR or is room left for others to have their ‘caramel or nut toppings’?
&gt;  
&gt; From: owner-shr-project-list@lists.mitre.org [mailto:owner-shr-project-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
&gt; Sent: Friday, July 15, 2016 4:12 PM
&gt; To: Joey Nichols ; shr-project-list Standard Health Record 10x Project List 
&gt; Subject: RE: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; The SHR evolves from day one.
&gt; As the new capabilities emerge from labs and require new data, those requirements migrate into the SHR.
&gt; Yes?
&gt; ...H
&gt; 
&gt; From: owner-shr-project-list@lists.mitre.org  on behalf of Joey Nichols 
&gt; Sent: Friday, July 15, 2016 3:44:53 PM
&gt; To: shr-project-list Standard Health Record 10x Project List
&gt; Subject: From SHR to the Precision Health Record (after Eric Topol)
&gt;  
&gt; http://ift.tt/29X3UWk
&gt;  
&gt; "I consider precision medicine digitizing you and me: Getting extraordinary deep, rich data about each person so you can come up with better prevention, screening, and treatment."
&gt;  
&gt; Here's an argument for what I've previously called The SyntheticSelf. A hyper-personalized Standard Health Record that facilitates prediction of future health states and forecasting of the comparative effectiveness of treatment alternatives.
&gt;  
&gt; If SHR is satisfied with representing the kinds of information that doctors use(d) presently and in the past, it will fall short of facilitating the care of patients under the Precision Medicine paradigm. 
&gt;  
&gt; Perhaps "Standardization" sets the wrong tone.
&gt;  
&gt; Are we building the Precision Health Record? If we do not, someone else will.
&gt; 
&gt; -JSN-
&gt; 
&gt; Joey Nichols
&gt; jsnichols@gmail.com
&gt; 713.398.5225
&gt;  
&gt; <br><br>
via Email <br>
July 15, 2016 at 11:10PM

**Comment by markkramerus** [comment]
Can you boil this down? I like the idea of captuing the email thread, but next time, try to capture the gist in the issue, and put the email thread in a comment.

**Comment by susanhaas** [comment]
Topics in thread: 
1 does the SHR evolve in content collected? Yes, from day 1 
2  in what ways can what we out in our repository (my term--is this fundamentally accurate? Mark described it as a vocabulary and grammar) be used FUNCTIONALLY to improve the health of individuals and populations?  I see us needing to keep the evolving as yet unimagined  uses in our minds at all times even as we create a standard representation of information. 
Does that capture the thread?
Susan

**Comment by jsnichols** [comment]
Thanks for the feedback Mark and the nice summary Susan.

I think Harry's ask is something akin to a product development timeline, describing which additional features are going to be added in v1.0, 2.0, 3.0, etc. I do not think this is fully knowable now. 

We have previously captured this timeline as: identification -> ER -> primary care -> inpatient -> genomics / everything else. **Is this good enough for now?** 

I think when we have a partner who early-adopts our SHR prototype, we will have clear pull requests to address. I think we are nearing the prototyping stage. (Soon?)
