### ISSUE TITLE
Would SHR achieve better than 80% accuracy?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#23]
80% of Canadians surveyed agreed that electronic records provide accurate information to their doctors. (Would SHR achieve better?)

75% of Canadians believe EHRs help doctors diagnose more effectively and allow for safe and secure sharing of information with patients, pharmacists, other doctors and specialists. 

Canadians’ attitudes towards EHRs are overwhelmingly positive, but **_more than 50% of respondents couldn’t say if their family doctor used an EHR or not**_.

73 percent of Canadian primary care physicians use EHRs.

...H

---

From: MobiHealthNews joe@mobihealthnews.ccsend.com on behalf of MobiHealthNews news@mobihealthnews.com
Sent: Tuesday, July 12, 2016 4:33:45 PM
To: Sleeper, Harry A.
Subject: | 07.12.2016 | Cisco telehealth spinoff gets $11M; OTC FDA clearance for Kegel exerciser 

Having trouble viewing this email? Click here 

Survey: Most Canadians want, but do not use, digital health tools
By Heather Mack

They may want it, but, for one reason or another, they aren’t using it. While nearly 90 percent of Canadians said in a recent survey that they want digital health technologies – believing it leads to better healthcare – only a small percentage are actually taking advantage of tools, according to a recent survey of over a thousand Canadians.

The survey of 1,009 adults, which was conducted by Maru/VCR&C and commissioned by Telus Health, found at least 85 percent of Canadians aren’t taking advantage of the digital tools available, such as accessing their electronic medical records via a portal. At least half of them weren't even aware that such services were already available at medical offices, clinics or pharmacies in some parts of the country.

When it comes to top-ranking online activities, fewer than half of Canadians spend their time accessing medical records. This is slightly below how much time they spend on social media and shopping, and far below personal banking (where 75 percent of Canadians spend their time online).

That’s not because they don’t trust EHRs. The majority of Canadians (80 percent) surveyed agreed that electronic records provide accurate information to their doctors. Three quarters of them believe EHRs help doctors diagnose more effectively and allow for safe and secure sharing of information with patients, pharmacists, other doctors and specialists. Canadians’ attitudes towards EHRs are overwhelmingly positive, but more than half of respondents couldn’t say if their family doctor used one. (According to a 2015 Canadian Institute for Health Information study, 73 percent of Canadian primary care physicians use EHRs).

"Both physicians and patients have significantly changed their attitudes towards digital communication over the past few years," says Dr. Sacha Bhatia, a cardiologist in Toronto said in a statement about the survey. "Doctors are much more comfortable communicating with patients and other healthcare providers using electronic means. I also think patients have seen the benefits of the internet and online services in their daily lives, and they expect to be able to have those same benefits when accessing health services."

Cisco spinoff Avizia raises $11M to expand telehealth offerings
By Heather Mack

Reston, Virginia-based Avizia has raised $11 million in Series A funding, bringing the telemedicine company’s total funding to $19.5 million. The funding round, led by Blue Heron Capital, also included Lavrock Ventures, NextGen Venture Partners, Middleland Capital, Waterline Capital and Blu Ventures.

"Telemedicine adoption is rapidly accelerating as health systems compete to offer more specialized care and reap the benefits of lower costs, improved access, and greater patient satisfaction." Blue Heron Capital Partner Tom Benedetti said in a statement.

Founded in 2013, Avizia spun out of Cisco and takes an approach similar to that used by Carena and Honeywell, which offer managed telemedicine offerings for providers. By combining all the elements of a telemedicine offering into one package, Avizia offers an end-to-end platform that links mobile software, as well as traditional carts and peripherals, into a healthcare provider’s EHR and back-end systems.

"When we looked to invest in the market, it was clear that Avizia was the right fit for us," Benedetti said in a statement. "Their differentiated software platform offers health systems greater flexibility, more use cases and superior integration."

This funding round will enable Avizia to further expand its telehealth video collaboration offerings for hospitals and physicians. Currently, the company has deployed its offerings across 36 countries. 

"Improving patient care is at the heart of everything we do," Avizia CEO and co-founder Mike Baird said in a statement. "To deliver on that promise, we’re focused on building an end-to-end telehealth platform that enables any provider to see any patient in any place."

Amino launches free, online healthcare cost comparison tool
By Jonah Comstock

Amino, a San Francisco-based startup that has built a free, online direct-to-consumer tool for finding a doctor, has added a cost estimator module to its offering. To begin with, the feature will calculate costs for 49 procedures and treatments, though more will be added over time. It includes 500,000 doctors nationwide and 129 health insurers.
The company uses claims data, algorithms, and human statisticians to calculate costs and quality scores. For the Cost Estimator, they analyzed $860 billion dollars in claims, comprising hundreds of millions of claims.
A number of healthcare price transparency tools have been offered over the years, including some very high-profile businesses like Castlight Health. But Amino CEO David Vivero says Amino stands out because other tools are so often offered by providers, insurers, and employers. A free tool on the Internet is going to more effectively reach consumers where they are, he believes. In addition, Amino's tool pairs cost transparency with quality transparency.
"It’s not really transparency if it’s hidden behind all sorts of password protections and portals and it’s so difficult to find that you can’t really gain access to the information," he said. "So the first thing we do that’s very different is that we’re going direct to consumers and making this information available to everyone on the web for free. ... The second thing that we do is we integrate our cost information into a very useful companion product. It incorporates cost and experience information and some quality measures, and you can book an appointment directly from the app. So the experience for us is not just about cost and cost transparency, but about integrating that with the overall patient experience and putting it in a place where consumers go to consume it."
That's not just a guess, Vivero said. Amino did market research to find out how consumers who do comparison shopping for healthcare behave.
"We interviewed 1,500 or so consumers and we asked them 'Have you price shopped in the past year?'," he said. "Forty percent of people said that they did. Well, what was interesting is that 60 percent of those people went to the internet to try to find this information. Only 8 percent went to an employer-sponsored portal, which is typically where healthcare transparency has been marketed these past few years."
Amino doesn't have a native app, but its website is optimized for mobile viewing. Vivero said it was important that the tool be accessible from the doctor's office itself, where patients often need to make treatment decisions.
"if you can search Facebook or Instagram from your doctor’s front desk, on your phone, you can pull up our app as well, he said. "So what’s great about the convenience and the distribution of Amino directly to consumers is that you can have this conversation with your doctor in the waiting room or in the consult room as they’re giving you a list of recommendations. And as such, our hope is that we can help people prevent out-of-network referrals that really cost them a lot of money, but also [help people] incorporate the idea of cost and quality into a discussion with their doctors."
The tool is designed to be able to show both overall costs and what's often more relevant to the consumer: their out-of-pocket costs. While it's most accurate for a consumer who has all the details of their health plan, including how much of their deductible they've used, the cost transparency tool will give estimates even if the user only knows the name of their plan. Users can see costs displayed on a map, so they can make decisions about how far they're willing to travel to save on a given procedure. And different doctors are color-coded green, yellow, and red based on their price relative to the region average.
Amino is still developing its business model, but Vivero says he's committed to never include advertising or allow a provider to buy a more prominent ranking. Instead, they plan to embrace a freemium model wherein they will introduce bonus features that users can pay for. The search tools will remain free.
"We haven’t monetized the site yet. There’s not the same pressure to do that because it’s such a long term bet that we and the investors are making," Vivero said. "The goal is to build a product and a set of features that consumers trust and recommend and flock to for their healthcare decision-making because it lets them know that they’re making the best possible choice. Based on that relationship we think there’s numerous services that we can introduce into the marketplace, so we’ll be doing that over time."

Analytica gets over-the-counter FDA clearance for smartphone-connected pelvic floor muscle trainer 
By Jonah Comstock

Analytica's PeriCoach, a smartphone-connected Kegel exercise coach for women, has received a second FDA 510(k) clearance, one that allows it to be sold over-the-counter. Its previous clearance, from March of last year, was for prescription use only.

Keep reading>>

Report: Eye and gesture tracking sensors are a $5B market 
By Heather Mack

Eye-tracking and gesture sensors are set to mark the next stage of innovation in machine design, according to new data from ABI Research. Just like touchscreens took over where the hand-controlled PC mouse left off, sensor technology is will change the way people interact with machines and systems. Bolstered by the ability to integrate with smartphone and tablet sensors, ABI forecasts the industry to hit $5 billion in 2016. 
Opportunities abound in healthcare, consumer electronics and automotive technologies, but healthcare in particular offers up the largest area for innovation, the research says.
"Healthcare professionals are relying on these sensors to move away from subjective patient observations and toward more quantifiable and measurable prognoses, revolutionizing patient care," Jeff Orr, research director for ABI said in a statement.
Implementing sensor technology can enhance diagnoses and therapeutic treatments. Eye-tracking sensors can help detect conditions such as concussion and enable vision therapy programs for childhood learning challenges. Gesture sensors can translate sign language into speech, allow doctors a means to manipulate imaging hands-free during surgical procedures (such as Atheer’s augmented interactive reality, or AiR glasses) and also enable navigation through virtual reality.
Innovation in the sensor sector is coming from both established and startup companies, with most being early on in their development stage. Several companies – including Leap Motion, Right Eye and Neurotrack – are developing imaging and eye-tracking software, and many others are involved with creative gesture and proximity solutions that utilize virtual reality. Other companies working on gesture technology for operating rooms include GestSure and Alvo.
Keep reading>>

```
July 12, 2016
```

Top Headlines

Survey: Most Canadians want, but do not use, digital health tools

Cisco spinoff Avizia raises $11M to expand telehealth offerings

Amino launches free, online healthcare cost comparison tool

Analytica gets over-the-counter FDA clearance for smartphone-connected pelvic floor muscle trainer

Report: Eye and gesture tracking sensors are a $5B market

This email was sent to sleeper@mitre.org by news@mobihealthnews.com
Update Profile/Email Address | Instant removal with SafeUnsubscribe™ | Privacy Policy.

HIMSS Media | 2 Monument Square Suite 400 | Portland | ME | 04101

**Comment by susanhaas** [comment]
How can we learn about their workflows, EHR system(s)?
We lack Canadians on our BRP at this time, yes?
