### ISSUE TITLE
Someone attend HSPC meeting Sept 28-30 in Phoenix, AZ

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#25]
HSPC Meeting – September 28-30 – Phoenix, AZ
Please join us for our next HSPC meeting, September 28 – 30 in Phoenix, AZ. The meeting will be held at the Scottsdale Conference Center and Resort.

Please note that in order to cover the costs of the meeting, there will be a $300 registration fee per person. Registration information forthcoming.

HSPC Agenda 201509

**Comment by mquilty** [comment]
I took a look at the agenda...there is a mix of technical and other...let me know if we need to send someone senior and or tech otherwise happy to go and take notes

**Comment by mquilty** [comment]
Given the timing - is this conference no longer an option and we can close this issue?
