### ISSUE TITLE
Submit a paper on SHR to ACI Special Issue on Interoperability and EHR

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#33]
From: "Walonoski, Jason A." jwalonoski@mitre.org
Date: Wednesday, June 29, 2016 at 7:55 AM
To: Mark Kramer MKRAMER@mitre.org
Cc: Andre Quina aquina@mitre.org
Subject: Paper for SHR?

https://chat.fhir.org/#narrow/near/24298/stream/Announcements/topic/ACI.20Special.20Issue.20on.20Interoperability.20and.20EHR

Announcements > ACI Special Issue on Interoperability and EHR

Koray Atalag: Dear FHIR community,

I'd like to give a heads up to the call for papers to the special issue on Interoperability and EHR in Applied Clinical Informatics. Prof. Kerstin Denecke from Bern University of Applied Sciences and I are guest editors and the aim of this special issue is to have informed and balanced papers on the theory and practice of standards to achieve interoperability and to develop EHR systems (that are intraoperable with Grahame's token). Deadline is 15 January, 2017.

Link to call for papers (pdf): https://aci.schattauer.de/fileadmin/assets/zeitschriften/ACI/CFP_ACI_Interoperability.pdf

Summary: The recent focus on HL7’s emerging Fast Healthcare Interoperability Resources (FHIR) has directed attention on the fact that attempts to achieve interoperability have been only partly successful in the past despite a host of existing terminologies (for example SNOMED CT, ICD and LOINC) and standards for health information exchange and EHR (HL7 v2,v3/CDA, openEHR/13606, IHE, DICOM etc.). This special topic feature of Applied Clinical Informatics will focus on applied, practical approaches of achieving and maintaining interoperability among disparate systems, including EHRs. We are soliciting submissions that focus on best practice approaches, lesson learned or evaluation of interoperability and EHR systems development or identify causes of failures.

**Comment by jsnichols** [comment]
Is this a venue for detailing the SHR? If not, what if anything can we release?

-JSN-

Joey Nichols
jsnichols@gmail.com
443-579-7779

**Comment by susanhaas** [comment]
And to whom?  What is the space between Mitre confidentiality in all work
and desire to publicize this work?

**Comment by markkramerus** [comment]
I think it is entirely suitable to submit a paper if we have worthwhile, concrete things to say.
