### ISSUE TITLE
We need a story for Rich B on how SHR & OHDSI compliment each other

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#34]
From: Sleeper, Harry A. 
Sent: Wednesday, June 29, 2016 2:04 PM
To: Quina, Andre C. aquina@mitre.org; Walonoski, Jason A. jwalonoski@mitre.org; Kramer, Mark A. MKRAMER@mitre.org; Quilty, Mary T. mquilty@mitre.org
Subject: RE: Paper for SHR?

Important.

We need to CLOSE the link with OHDSI.  (OMOP)
In the works?....H

The Observational Health Data Sciences and Informatics (or OHDSI, pronounced "Odyssey") program is a multi-stakeholder, interdisciplinary collaborative to bring out the value of health data through large-scale analytics. All our solutions are open-source.

**Comment by markkramerus** [comment]
From: owner-standard-health-record-10x-list@lists.mitre.org [mailto:owner-standard-health-record-10x-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
Sent: Sunday, June 26, 2016 11:34 PM
To: standard-health-record-10x-list US Standard Health Record Design <standard-health-record-10x-list@lists.mitre.org>
Subject: Health Data Standardization with OHDSI

http://www.ohdsi.org/data-standardization/

Mark----We will need a story for Rich B on how SHR & OHDSI compliment each other.

...H

**Comment by mquilty** [comment]
Hi Mark, 
Can you let me know where this is? I have this email chain as a direct email to: Andre, Jay, you, and I. Do I have an active ask or are you working on this item?

Thanks, 
m
