### ISSUE TITLE
Help Gabe Galvin pitch SHR to the nation of Qatar

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#41]
From: owner-hdi-10x-list@lists.mitre.org [mailto:owner-hdi-10x-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
Sent: Tuesday, June 14, 2016 4:41 PM
To: hdi-10x-list Health Data Interoperability 10X Initiative hdi-10x-list@lists.mitre.org
Subject: FW: HDI-10x Proposal

Gabe is on board.
He also wants to use SHR with the nation of Qatar.

…H

From: Galvan, Gabriel F. 
Sent: Monday, June 13, 2016 5:24 PM
To: Potter, Charles cpotter@mitre.org; Honess-Morreale, Lauren R laurenhm@mitre.org
Cc: Sleeper, Harry A. sleeper@mitre.org
Subject: FW: HDI-10x Proposal

Chuck,

You asked me about electronic health records.  Harry Sleeper and team are working on this concept supported by our corporate officers to advance.  I understand Harry has pitched it to Yosry.  

For your ‘listening’ session with Richard tomorrow, this might be a small opening to have in your back pocket, knowing that MITRE wants to engage with the VA do support this kind of initiative.  Feel free to reach out to Harry (based in Bedford) if you have questions.  While I don’t think you need to sell Dr. Stone on the concept’s value, it might be something your conversation gravitates towards given your respective work on DoD health records.  It would be a good addition to a list of items to reengage soon with him.

Regards,
Gabe

From: "Sleeper, Harry A." sleeper@mitre.org
Date: Monday, June 13, 2016 at 5:08 PM
To: "Galvan, Gabriel F." ggalvan@mitre.org
Cc: "Sleeper, Harry A." sleeper@mitre.org
Subject: HDI-10x Proposal

Gabe

We are pushing on a 10x initiative to help solve 
Health Data Interoperability in the US (and beyond).

The core concept is to build a 
Standard Health Record for all Emergency care, 
Primary care, and, in time, other domains of healthcare delivery.

Please review the attached charts.
We'd like to brief you and get your support.

...H

**Comment by mquilty** [comment]
Could Qatar be a pilot site for the very core (or more) of the SHR? It’s International (a MITRE goal) and a somewhat isolated sample population with sovereign status that may support quick PHI approval (SHR goal). 

Some fun facts about Qatar: 
•	The National Health Authority (NHA) was established in 2005 to replace the Ministry of Public Health. 
•	The NHA overseas the necessary medical services and entrusts them to public health institutions, the main one being the Hamad Medical Corporation (HMC).
•	There are ~9 hospitals, ~5 are government run
•	Ambulance service is strong and linked to at least one major hospital via satellite 
•	NHA controls make/market of drugs and conforms to international standards
•	Belief in preventive care and vaccines; country spends on healthcare
