### ISSUE TITLE
Start an SHR Partners Program with Certification Logo

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#45]
From: Sleeper, Harry A. 
Sent: Saturday, July 16, 2016 12:35 AM
To: Kramer, Mark A. MKRAMER@mitre.org; Walonoski, Jason A. jwalonoski@mitre.org; Quina, Andre C. aquina@mitre.org
Subject: FW: Prepare for the future of on-demand healthcare

Could we start a SHR Partners Program.
Add a logo if a group signs the "SHR: Intent to Test Pledge"?
We collect endorsements from as many HIT vendors as possible?

---

From: Corepoint Health information@corepointhealth.com
Sent: Friday, July 15, 2016 2:32:26 PM
To: Sleeper, Harry A.
Subject: Prepare for the future of on-demand healthcare 

Demand for rapid data exchange will only continue to grow as technical innovation further impacts health care.

Hi Harry,
Interfacing standards and expectations are changing.
Patient behavior and growing popularity in telehealth, mobile apps and smart devices have increased the pressure for healthcare providers to deliver accurate, on-demand data.
Demand for rapid data exchange will only continue to grow as technical innovation further impacts health care.
Ensure your interfacing strategy aligns with future market direction in the new ebook: "Preparing for the On-Demand Future of Health Care".

This ebook focuses on four areas:
• Building a connected foundation
• Establishing a strategic data framework 
• The latest in health data standards 
• Value of an upgraded interface engine 
View the ebook now!
As always, feel welcomed to request more information or schedule a demo of Corepoint Integration Engine.
Thank you,
Corepoint Health
information@corepointhealth.com
214-618-7000
KLAS® Category Leader in Interface Engines, 7 Consecutive Years     

Corepoint Health   3010 Gaylord Parkway  Suite 320  Frisco,  TX   75034   USA 

You received this email because you are subscribed to Marketing Information from Corepoint Health. 

Update your email preferences to choose the types of emails you receive. 

 Unsubscribe from all future emails

**Comment by mquilty** [comment]
A pledge to increase health data opportunity to achieve the triple aim seems reasonable for folks to buy into…it also feels like something the BRP could potentially kick-start…rather than their signing a list of SHR recommendations, they could sign off on their support/pledge to move this work forward…nice momentum for the “partner program”.
