### ISSUE TITLE
We need to actively work industry transition scenarios

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#47]
From: owner-shr-project-list@lists.mitre.org [mailto:owner-shr-project-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
Sent: Friday, July 15, 2016 9:25 PM
To: Joey Nichols jsnichols@gmail.com
Cc: Quina, Andre C. aquina@mitre.org; shr-project-list Standard Health Record 10x Project List shr-project-list@lists.mitre.org
Subject: RE: DoD Standard Health Record Proposal

We need to actively work industry transition scenarios, now.
That was one of the very critical questions by Micky Tripathi, our very first SHR Blue Ribbon Panel member (!!!!).

Micky Tripathi also strongly advocated for a "Build the SHR for DoD/VA First" strategy. 
Exactly as Baha Fam laid it out.
My one caution----We must simultaneously work the civilian market----It's larger, more complex, and it has very strong consumer pressure to rapidly improve SHR (think Rapid Evolution). 
It also COSTS the most.

We also need to use the civilian interoperability needs of DoD/VA to actually influence DoD/VA decisions w/r/t SHR. It's a bit of a circle...

Who will use more genomics on a regular basis in the early adoption cycle: DoD, VA, or civilian providers?
Please vote now.

...H

---

From: Joey Nichols jsnichols@gmail.com
Sent: Friday, July 15, 2016 5:38:05 PM
To: Sleeper, Harry A.
Cc: Quina, Andre C.; shr-project-list Standard Health Record 10x Project List
Subject: Re: DoD Standard Health Record Proposal 

I like this, too.

It's nice to see us leveraging the Cerner decision to advance SHR, both within a sponsoring agency and within a top 2 vendor. Brilliant.

I like also that this approach opens us up immediately to disseminate SHR into VA and civilian systems. This is an uncontroversial horizontal integration strategy. Nice.

I recommend a greater focus on "We are not just delivering a data model; we are going to show how you will migrate from present state to SHR." I think this is what you mean by "Resolution Plan."  

Message to Sponsors: Let's get you there. (That's what I think we mean by "MITRE Work." At least I hope so.)

-JSN-

Joey Nichols
jsnichols@gmail.com
713.398.5225

On Fri, Jul 15, 2016 at 5:13 PM, Sleeper, Harry A. sleeper@mitre.org wrote:
Good first draft!

Rob---Next week, if possible, do Intel and provide Andre feedback.

...H

---

From: Quina, Andre C.
Sent: Friday, July 15, 2016 4:51:23 PM
To: Sleeper, Harry A.
Cc: shr-project-list Standard Health Record 10x Project List
Subject: DoD Standard Health Record Proposal 

Attached is the first draft of a DoD Standard Health Record proposal.

Andre

**Comment by susanhaas** [comment]
Civilian
