### ISSUE TITLE
What are the Blue Ribbon Panel Funding Needs?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#51]
From: owner-shr-project-list@lists.mitre.org [mailto:owner-shr-project-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
Sent: Friday, July 15, 2016 9:10 AM
To: Quina, Andre C. aquina@mitre.org; shr-project-list Standard Health Record 10x Project List shr-project-list@lists.mitre.org
Subject: RE: Presentation for Micky

On the charter:
Great draft!
Treat as an online open source document with version control, please.
Not a stodgy, paper-based legal document collecting dust.
Ok?
I do NOT buy into the lock down mindset.

We need to keep the BRP member load to an absolute, essential minimum. We are not there yet.

What is the BRP funding needs?

On the BRP schedule:
We need to sync with a master SHR-10x schedule.

...H

---

From: owner-shr-project-list@lists.mitre.org owner-shr-project-list@lists.mitre.org on behalf of Quina, Andre C. aquina@mitre.org
Sent: Friday, July 15, 2016 8:48:41 AM
To: shr-project-list Standard Health Record 10x Project List
Subject: Presentation for Micky 

Attached is the final presentation for Micky and the charter for the Blue Ribbon Panel.  I plan to bring printed copies of the charter.

Andre

**Comment by mquilty** [comment]
Potential BRP costs: 
Honorarium (needed?)
Logistics (hotel, air, ground transport, per diem, meals) - for members and MITRE team 
 - the more we require in-person meetings the higher this gets (and how far from the meeting place)
Venues and related costs to host meetings
Conference fees (e.g., if we made a HiMMS meeting count as a session)
Staff time to support BRP requests (content, operations, admin)

**Comment by mquilty** [comment]
Aiming to have SHR team strategy sessions to flesh out the larger work plan and develop a schedule - specific goals from, and asks to, the BRP could drive what needs to sync up with the BRP meetings (e.g., development schedules and demos, plans for who to reach out to)
