### ISSUE TITLE
Income, Occupation + Education = required, top-level data points

### ISSUE THREAD

**Issue by jsonin** [standardhealth/shr_design#69]
With income and education level as the top signals of "health", they need to be top-level data points in the SHR. Move from "add later" to "high priority" data.

**Comment by susanhaas** [comment]
Are they epiphenomena?  I don't know the answer.  Is zip more predictive?  Given the interaction, would love to pull those factors in in priority order....

**Comment by markkramerus** [comment]
Need to change in SHR briefing deck.
