### ISSUE TITLE
Script video

### ISSUE THREAD

**Issue by mquilty** [standardhealth/shr_design#7]

**Comment by markkramerus** [comment]
Hi

No footage of me exists.
Not many photos. :--0

I vote for:
Let's tape Mark Kramer giving the core of the SHR message---a 3 minute blurb with a 15-20 minute full version.
More SHR, less MITRE.

Release immediately on Git Wiki as part of our continuous collaboration.

...H

PS
Mary----We need to finding funding for Partners ConnectedHealth.

PSS
We must position SHR wrt OHDSI CDM. ASAP.
________________________________________
From: Quilty, Mary T.
Sent: Monday, June 27, 2016 2:36:09 PM
To: Sonin, Juhan P.
Cc: Sleeper, Harry A.
Subject: Partners Connected Health Conference 
 
Hi Juhan, 
 
I spoke with DeAnna from Partners Connected Health Conference today. OHS was talking about having a formal presence there this year (exhibitor booth, private room for promoting SHR, etc.).
While on the call DeAnna mentioned that she spoke with you concerning Harry as a possible panel presenter this year or next. She asked if there was footage of Harry. 
 
Writing to let you know she and I spoke and to see if you were following up on her Harry request.  
 
Thank you and take care, 
Mary 
 
Mary T. Quilty, SM
Lead Healthcare Policy Analyst, Health Standards & Interoperability 
Health Transformation Technology Center
The MITRE Corporation
Bedford, MA 01730-1420
                  (781) 271-4793– Office
                  (781) 408-9024 – Mobile/Text
Email:      mquilty@mitre.org 
Website:  www.mitre.org 
…working in the public interest…

**Comment by markkramerus** [comment]
Closed by mistake, reopened.

**Comment by mquilty** [comment]
Requirements for 3 min video: 

•	Script
o	Overarching message and say 3 key takeaways
o	Call to action?
•	Visual (static or select briefing screens)
o	Note: if we are close to a logo that would be great to include
•	Position of visual (who is center stage – Mark or the visual – or does it alternate?)
•	Public release – script and video needed? 
•	Harry said this is for Git Wiki
o	Setup a new one or use MITRE’s
	Open Source software from The MITRE Corporation at GitHub https://mitre.github.io/
	How is this connecting to a greater communications plan – does it matter?
•	Does 3 min video connect to the larger 15 min video in a meaningful way (e.g., flesh out the outline introduced in the 3 min)
•	Logistics
o	Well-rehearsed and ready to rock it Mark
o	Room
o	Sound quality
o	Light quality
o	Video and video quality; editing needs?

**Comment by mquilty** [comment]
Can animation be included in the video? Are the 1 pagers starting to build what could be the basis of a script? what are the key points for the video and where is it going to be posted - MITRE youtube? SHR website? Github page?
