### ISSUE TITLE
SHR Presentation at Baltimore Site in August

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr_design#77]
**My Recommendations**
- Identify a high profile speaker (HPS, e.g. Micky Tripathi) to participate in an August SHR Tech Talk at Baltimore
- Market with give-aways, which may include: book authored by the HPS (if s/he wrote one), a book that gives relevant SHR background (e.g. Eric Topol's?) free to first 15 participants, SHR-branded swag (e.g. coffee mug, SHR logo lapel pin to go on MITRE landyard, etc.), Amazon gift card raffle (i.e. must be present to win)
- Differentiate Tech Talk from the SHR Lunch and Learn by making the former less technical, oriented around a narrative of a synthetic patient using SHR to navigate the health care system
- HPS leads with 10 minute high level overview of the interoperability problem, with emphasis on policy landscape. 5-10 minute Q/A follows. This is in Baltimore or via teleconference.
- @markkramerus / @andrequina follow with a 20 minute walk through of a patient and her clinicians interacting with the SHR. 10-15 minute Q/A follows. This is in Baltimore.
- @markkramerus / @andrequina / maybe HPS are available for ad hoc vs pre-scheduled break out sessions with Program and Portfolio folks to discuss SHR 

**Contacts at Baltimore Site**
- Susan Hall, Baltimore Site Operations Lead
- Theresa Sheffey, Adminstrative Support Specialist
- Katurah Bland, Meeting Coordinator

**Dates**
- Mondays - "Crazy"
- Tuesdays - "Best"
- Wednesdays and Thursdays - "Okay"
- Fridays - "Ghost Town"
- We felt good about a 25 person turn-out for Schimpff's talk. Meanwhile social recognition events are typically scheduled on Tuesday and usually draw 60, sometimes 80
- There is a question of having the **most** participants, versus the **right** participants.
- Do not schedule on these dates: Aug 11-12, Aug 31
- A Tues or Wed would be hard for @jsnichols, but not impossible

**Rooms**
- We had 25+ people in 202, which is at capacity for that room
- 40+ people can fit in 102/104, 209/210/211
- Can book on RRS 
- Can FJ: Baltimore for information on room layouts
- Can ping Katurah Bland for additional assistance
- Can cater with Foodify (local restaurants bid, lots of good options, can use project charge code)

**Marketing strategy**
- A high profile speaker is a draw
- Many participants came because their bosses encouraged them to do so
- “Books motivate people” … “or just a gift card [raffle]” … “now you’ve spoiled them” ... i.e. the books were a hit; however other kinds of swag have been effective in the past
- Is this an opportunity to produce/distribute SHR swag? What can we give away that would increase SHR visibility? (And eventually become a collectors item? What will a @jsonin designed coffee mug go for on Ebay someday?)
- People didn't recognize @jsnichols as a Tech-Talk-brand before, maybe this will develop in the future

**Format**
- There was feedback that we should “breaking [the talk] into sections” offering Q/A after each section, since Q/A is perceived as high value, but some participants get pulled away and can't participate if this is left until the end
- “Value of an anecdote” Talks that frame content in a personal story are well received (walkthrough of the SHR with test patient)

**Comment by markkramerus** [comment]
Mark K could do it Aug 16 or 19th.

**Comment by jsnichols** [comment]
Closing because this didn't happen. Although this is a useful guide for future reference.
