### ISSUE TITLE
Do we want to develop metrics to demonstrate success for the SHR?

### ISSUE THREAD

**Issue by mquilty** [standardhealth/shr_design#81]
This is not unlike milestones, but speaks more to the emails earlier re: adoption rates and expectations...short term through long term metrics - maybe long term is goal state for now...but articulating the goal concretely can help plan for the now.

**Comment by susanhaas** [comment]
Great idea, Mary.
Naive to such projects I'll toss out a few ideas and questions so people can respond:
1. who/where will the SHR be 'hosted' (if that is the correct term)?  Will it be at a .gov, a .org, or at a .com?  Or will any willing entity (eg Vermont, eg Amazon, eg athenahealth eg BCBS combined blue plans of america)
2. If any willing entity then measure will be how many entities and how many patients have their data 'enrolled'
3. percent of defined data elements currently filled broken down by those that never change (immunization was given/when) and those that fluctuate.
4. number/rate of growth of access of each data element.
......
