### ISSUE TITLE
HL7 versus SHR approach to Care Plans

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr_design#90]
So I skimmed this whole DAM thing, and HL7's concept of what a care plan is and how it works is similar to SHR's. 

http://wiki.hl7.org/images/1/1d/PCWG_Care_Plan_DAM_Specification_-_Part_1_-_Draft_2015-11-04.pdf

There is precious little here to guide us with modeling. 

Most of the pages of this document are dedicated to describing (in text?) some well thought out "story boards" that highlight important scenarios where care planning is useful. I like the "story boards," in so much as they are a great reference point for how health care is delivered today. 

Overall, I sense HL7 is preoccupied with representing how Care Plans are documented today. (Remember that today, mostly Care Plans are not well represented or shared.) There does not appear to be much imagination about what could be (or should be, probably group think plays into this.) HL7 seems to want to create a good-enough-thing-that-can-be-shared. 

HL7 PCWG DAM states that the care planning process is out of scope. This is shortsighted. While it is not the role of the HL7 or SHR Care Plan specification to specify any single way that Care Plans must be negotiated between patients and other actors (this is neither possible nor desirable), there are elements of data and metadata that enable specialized functions during the negotiation and implementation of Care Plans. 

So apart from the technical innovations we will introduce through SHR spec, the scope of SHR use cases for Care Plans needs to be broader.

Stated another way, as a clinician I am not satisfied simply to see that Care Plans exist. The Care Plans will not create themselves, and merely having one won't guarantee that the condition of the patient is improved. **The SHR technical approach must therefore facilitate easy creation, revision, monitoring and implementation of Care Plans from the perspectives of all users.** 

I will also encourage SHR Care Plans to support policy level changes in the way that health care is organized and financed. A vision for the Care Plan / SHR is that current approaches to reimbursement (i.e. reimbursement driven by claims process) could be replaced by monitoring of quality / outcomes / utilization directly from Care Plans. **The Care Plan integrates data for financial, operational and clinical purposes, facilitating reimbursement, patient care, quality/safety, population health monitoring/improvement and patient engagement functions of a learning health system.**

Divorcing provider reimbursement from EHR generation of progress notes and billing claims is a crucial capability, since it disrupts the current raison d'etre for today's EHRs that everyone hates. EHR vendors will be forced to pivot to business models focusing on data security, visualization, UI/UX, business/clinical process support, population health intelligence, etc. because the Care Plans get providers paid.

**Comment by dvanleeu** [comment]
I visualize person-centered care planning based on the following scenario:

I’m the child, Custodian and Healthcare Proxy of my 89-year-old mother, Alice. I live in a different state. My mother has diabetes and is depressed. Her care team, beside herself and me, includes medical providers in various health settings, community support agencies, and a full-time caregiver that helps her schedule and get to health-related services. My problem is to understand what my mother wants for herself and to track who on the health team says they’re doing something for her (including my mother and me), what they’re doing, and when they’re doing it. I want to know what it takes to do it (Can she afford it? Can she get there? Does it agree with her? Who will be with her? etc.). I want to know if the actions have been completed and do they have the effects we thought they would. I want to know what her risks are and how we plan to prevent or respond to them. I want to able to keep track of all this and keep it current. I want to share it or have it shared from day-to-day and from setting to setting and team member to team member even if I’m not present.

more attached

[Care Planning github 20170423.docx](https://github.com/standardhealth/shr_design/files/949685/Care.Planning.github.20170423.docx)
